name: elaine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  appwrite: ^20.3.1
  flex_color_scheme: ^8.3.1
  flutter_hooks: ^0.21.3+1
  flutter_modular: ^6.4.1
  visibility_detector: ^0.4.0+2
  get_time_ago: ^2.3.2
  url_launcher: ^6.3.2
  intl: ^0.20.2
  collection: ^1.19.1
  flutter_animate: ^4.5.2
  flutter_html: ^3.0.0
  super_sliver_list: ^0.4.1
  universal_html: ^2.3.0
  path: ^1.9.1
  bit_array: ^2.3.0
  linkify: ^5.0.0
  hashlib: ^2.2.0
  image: ^4.7.2
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
